one = ['Bergführer',
                 'Betriebspsychologe',
                 'Bierbrauer',
                 'Blogger',
                 'E-Sportler',
                 'Erlebnisgestalter',
                 'Escape Room Designer',
                 'Feng-Shui-Berater',
                 'Futurist',
                 'Geocacher',
                 'Hochzeitsplaner',
                 'Hundeflüsterer',
                 'Influencer',
                 'Kampfsporttrainer',
                 'Klettertrainer',
                 'Koch für Allergiker',
                 'Koch für exotische Gerichte',
                 'Konditor',
                 'Kreativdirektor',
                 'Kreativitätscoach',
                 'Krisenmanager',
                 'Kryptozoologe',
                 'Käsemeister',
                 'Landschaftsarchitekt',
                 'Mikrobiologe für Lebensmittel',
                 'Privatdetektiv',
                 'Professor für Sexuallehre',
                 'Reiseblogger',
                 'Reiseblogger',
                 'Sargmacher',
                 'Schauspieler für erotische Filme',
                 'Schnapsbrenner',
                 'Schnapsverkoster',
                 'Schnitzeljagd-Organisator',
                 'Schnorchelguide',
                 'Sicherheitsberater',
                 'Sinnesforscher',
                 'Spezialeffekt-Künstler',
                 'Sternenbeobachter',
                 'Sternenforscher',
                 'Stripper',
                 'Stuntman',
                 'Surflehrer',
                 'Tattoo-Künstler',
                 'Tauchlehrer',
                 'Trauerredner',
                 'Trendanalyst',
                 'Trendforscher',
                 'Voice-Over-Sprecher',
                 'Wildtierbiologe',
                 'Wissenschaftsjournalist',
                 'Zirkusartist']
two = [
  "Abenteuerpädagoge",
  "Arktis-Tourguide",
  "Bauernhof-Influencer",
  "Berater für Minimalismus",
  "Beruflicher Ausmist-Coach",
  "Bewusstseinsforscher",
  "Brückeninspektor",
  "Casinotester",
  "Cloud-Gärtner (Pflanzenpflege auf Dachgärten)",
  "Compliance-Trainer für Unternehmen",
  "Cyborg-Designer",
  "Data-Storyteller",
  "Digitale Nachlassverwalter",
  "Escape-Room-Gamedesigner",
  "Extremwetter-Forscher",
  "Fachkraft für Mikroabenteuer",
  "Falke für Flughafenschutz",
  "Freizeitpark-Tester",
  "Geisterjäger für historische Gebäude",
  "Glaskünstler für Spezialeffekte",
  "Horror-Event-Designer",
  "Insektenkoch",
  "Interstellarer Anwalt",
  "Katastrophenpsychologe",
  "Kaugummientferner-Spezialist",
  "Kletterwald-Instrukteur",
  "Konfliktmediation für Start-Ups",
  "Künstliche-Intelligenz-Trainer",
  "Luxus-Baumhaus-Designer",
  "Lügendetektor-Experte",
  "Mülltaucher für Recycling-Forschung",
  "Musik-Therapeut für Tiere",
  "Nuklear-Entsorgungsexperte",
  "Planetensystem-Modellbauer",
  "Podcasts-Schnitttechniker",
  "Prüfer für Sicherheit von Freizeitgeräten",
  "Sandburgen-Architekt",
  "Sicherheitsberater für autonome Fahrzeuge",
  "Smart-Home-Installateur",
  "Sprach-Coach für Sprachassistenten",
  "Stadtplaner für schwimmende Städte",
  "Taucher für Tiefsee-Reparaturen",
  "Tierfriseur für exotische Tiere",
  "Trend-Coach für Influencer",
  "Unterwasser-Fotograf",
  "Verpackungsdesigner für nachhaltige Produkte",
  "Virtual-Reality-Erlebnismacher",
  "Waldtherapeut",
  "Wasserrutschbahn-Konstrukteur",
  "Weltraum-Biologe",
  "Wildnis-Survival-Trainer",
"Abenteuerschatzsucher",
  "Algenzüchter für Bioenergie",
  "Astronautentrainer",
  "Bienenhoteldesigner",
  "Blitzfotograf",
  "Buchbinder für alte Manuskripte",
  "Dachbegrünungsexperte",
  "Drohnendesigner",
  "E-Sports-Kommentator",
  "Erdbeben-Ingenieur",
  "Extremhöhlenforscher",
  "Flussrenaturierer",
  "Futterberater für Haustiere",
  "Gebäudethermografie-Experte",
  "Geruchsberater für Unternehmen",
  "Geschichtenerfinder für Games",
  "Gewächshausdesigner",
  "Glaziologe (Gletscherforscher)",
  "Green-Event-Manager",
  "Hitzeschutzingenieur",
  "Hobbydetektiv-Ausbilder",
  "Hyperloop-Ingenieur",
  "Immersive-Theater-Regisseur",
  "Insektenhotelbauer",
  "Kaffeefarmer für Spezialsorten",
  "Kälteschutzforscher",
  "Kino-4D-Effekte-Designer",
  "Klimaanpassungsberater",
  "Kreativtherapeut",
  "Kulissenbauer für Freizeitparks",
  "Landschaftsgestalter für urbane Räume",
  "Lärmberatungsingenieur",
  "Luftfahrthistoriker",
  "Luxushoteldesigner",
  "Mars-Landwirtschaftsexperte",
  "Medienforensiker",
  "Meteoritensammler",
  "Mikroplastikforscher",
  "Molekularkoch",
  "Mondforscher",
  "Müll-Architekt für Recyclingkunst",
  "Nachhaltigkeitsberater für Mode",
  "Nano-Robotertechniker",
  "Ökotourismus-Manager",
  "Orchideenzüchter",
  "Pflanzen-Therapeut",
  "Pilzdesigner für nachhaltige Möbel",
  "Popkulturhistoriker",
  "Raumstationsarchitekt",
  "Regenwaldretter",
  "Robotertester",
  "Schildkrötenschützer",
  "Schlafberater",
  "Schneekanonenexperte",
  "Seifenblasen-Künstler für Events",
  "Sensorikforscher für Lebensmittel",
  "Simulator-Trainer für Piloten",
  "Smarte-Kleidung-Designer",
  "Sonnencreme-Entwickler",
  "Spezialdrohnenpilot",
  "Stadtbegrünungsexperte",
  "Sternehotel-Tester",
  "Stressmanagement-Coach",
  "Szenario-Designer für Planspiele",
  "Tierspurenexperte",
  "Traditionsforscher",
  "Trinkwasseraufbereitungsingenieur",
  "Unterwasserarchäologe",
  "Virtuelle-Avatare-Designer",
  "Vulkanführer",
  "Weltuntergangsberater",
  "Windpark-Designer",
  "Zukunftsarchitekt",
  "Zukunftsforscher für Mobilität"
]


resulting_list = list(one)
resulting_list.extend(x for x in two if x not in resulting_list)
for x in resulting_list:
    if resulting_list.count(x) > 1:
        resulting_list.remove(x)
resulting_list.sort()
print(resulting_list)
print(len(resulting_list))